// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaYvV1uFbD72Nwyf5HDqoVvSGcbqMI55E',
    appId: '1:1055328256561:web:4e003c24ffc00dd0014b10',
    messagingSenderId: '1055328256561',
    projectId: 'cloud-guard-63f42',
    authDomain: 'cloud-guard-63f42.firebaseapp.com',
    storageBucket: 'cloud-guard-63f42.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJc08-KW7ni3j4UMFpZsd2jnwSxbVL4KA',
    appId: '1:1055328256561:android:9e3ab6fa4e96c338014b10',
    messagingSenderId: '1055328256561',
    projectId: 'cloud-guard-63f42',
    storageBucket: 'cloud-guard-63f42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDucCcZTX2D6cbXPKZ4HOEUs7BupNbYYoU',
    appId: '1:1055328256561:ios:9eb260d0e2eba2be014b10',
    messagingSenderId: '1055328256561',
    projectId: 'cloud-guard-63f42',
    storageBucket: 'cloud-guard-63f42.firebasestorage.app',
    iosBundleId: 'com.example.cloudGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDucCcZTX2D6cbXPKZ4HOEUs7BupNbYYoU',
    appId: '1:1055328256561:ios:9eb260d0e2eba2be014b10',
    messagingSenderId: '1055328256561',
    projectId: 'cloud-guard-63f42',
    storageBucket: 'cloud-guard-63f42.firebasestorage.app',
    iosBundleId: 'com.example.cloudGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaYvV1uFbD72Nwyf5HDqoVvSGcbqMI55E',
    appId: '1:1055328256561:web:7a478dcf4ab0effe014b10',
    messagingSenderId: '1055328256561',
    projectId: 'cloud-guard-63f42',
    authDomain: 'cloud-guard-63f42.firebaseapp.com',
    storageBucket: 'cloud-guard-63f42.firebasestorage.app',
  );
}
